version: '3.8'

services: 
  mysqldb:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: helloworld 
      MYSQL_DATABASE: NswRegistrations
    ports:
      - 3389:3306
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-mysql-app
    environment:
      - NODE_ENV=production
    depends_on:
      - mysqldb
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

volumes: 
  db-config:
  db-data:
